### ISSUE TITLE
Package Pubilshing

### ISSUE THREAD

**Issue by splendido** [MeteorPackaging/ramda-wrapper#1]
@ccorcos, @kevohagan, @dandv, 
from my side, the package is ready for publishing.

Please have a look at it and feel free to publish in case you don't spot anything weird!

Cheers,
Luca

**Comment by ccorcos** [comment]
How do I update this package for the new version of Ramda? Shouldn't it update on its own with autopublish.meteor.com?

**Comment by bySabi** [comment]
:+1:

**Comment by ccorcos** [comment]
Version 17.1 now. How does this update?

**Comment by splendido** [comment]
...still manually :(
See [here](https://github.com/MeteorPackaging/autopublish.meteor.com/wiki/Wrapping-3rd-Party-Packages#version-bump) the sequence of commands to be run.

You have full rights to publish a new version, please do it

**Comment by ccorcos** [comment]
nice script! worked great :)

**Comment by splendido** [comment]
glad it worked :)

...just one minor glitch: see [this comment](https://github.com/MeteorPackaging/ramda-wrapper/commit/723b5001a977fb99df8ef3094f76a1b8c83b1bdf#commitcomment-12896295) ;-)

**Comment by ni-ko-o-kin** [comment]
Thx! Just added ramda 0.17.1 to my meteor project!

**Comment by CrossEye** [comment]
I don't know much about Meteor, but this just came up on the Ramda issues list:

https://github.com/ramda/ramda/issues/1375

Is this something that can be handled here, or is it likely user error?

**Comment by ccorcos** [comment]
Anything related to Meteor and Ramda should be referred to this package.
